% Auto-generated by cameraCalibrator app on 15-Sep-2016
%-------------------------------------------------------

global glob
% Define images to process
imageFileNames = {'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8629.JPG',...
    'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8630.JPG',...
    'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8631.JPG',...
    'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8633.JPG',...
    'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8634.JPG',...
    'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8635.JPG',...
    'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8636.JPG',...
    'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8638.JPG',...
    'D:\unipd\Esami\Image and video analysis\final_project\images\calibration\IMG_8642.JPG',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 32;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);
glob.cameraParams = cameraParams;
%{
% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
%}